
import { StageTemplate, TrackColor } from './types';

export const TRACK_COLORS: { label: string; value: TrackColor; bg: string; text: string; border: string }[] = [
  { label: 'Белая', value: 'white', bg: 'bg-slate-50', text: 'text-slate-900', border: 'border-slate-300' },
  { label: 'Желтая', value: 'yellow', bg: 'bg-yellow-400', text: 'text-yellow-950', border: 'border-yellow-600' },
  { label: 'Зеленая', value: 'green', bg: 'bg-emerald-500', text: 'text-emerald-950', border: 'border-emerald-700' },
  { label: 'Синяя', value: 'blue', bg: 'bg-blue-600', text: 'text-white', border: 'border-blue-800' },
  { label: 'Красная', value: 'red', bg: 'bg-red-600', text: 'text-white', border: 'border-red-800' },
  { label: 'Черная', value: 'black', bg: 'bg-zinc-900', text: 'text-white', border: 'border-zinc-700' },
];

export const STAGES_DATA: StageTemplate[] = [
  { name: 'Horizontal footbridge', color: ["yellow", "green", "blue"], emoji: "🌉" },
  { name: 'Duck Steps', color: ["yellow", "green", "blue", "red", "black"], emoji: "🦆" },
  { name: 'Net_s tunnel', color: ["yellow", "green", "blue"], emoji: "🕸️" },
  { name: 'Net_s path', color: ["yellow", "green", "blue", "red", "black"], emoji: "🎢" },
  { name: 'Monkey bridge', color: ["yellow", "green", "blue"], emoji: "🐒" },
  { name: 'Rolling logs', color: ["blue", "red", "black"], emoji: "🪵" },
  { name: 'Swinging Plates', color: ["green", "blue"], emoji: "🍽️" },
  { name: 'Horizontal ladder', color: ["yellow", "green", "blue"], emoji: "🪜" },
  { name: 'Giant’s step', color: ["yellow", "green", "blue"], emoji: "👣" },
  { name: 'Barrels', color: ["yellow", "green"], emoji: "🛢️" },
  { name: 'Japanese footbridge', color: ["yellow", "green", "blue"], emoji: "⛩️" },
  { name: 'Swinging trunks', color: ["yellow", "green", "blue", "red", "black"], emoji: "🌲" },
  { name: 'Flat net', color: ["yellow", "green", "blue", "red", "black"], emoji: "🕸️" },
  { name: 'Swings', color: ["yellow", "green", "blue", "red", "black"], emoji: "🪑" },
  { name: 'Surprise', color: ["blue", "red", "black"], emoji: "❓" },
  { name: 'Lengthwise logs', color: ["yellow", "green", "blue"], emoji: "📏" },
  { name: 'Swingplates and swings', color: ["yellow", "green", "blue", "red", "black"], emoji: "⚖️" },
  { name: 'Parallell stirrups', color: ["blue", "red", "black"], emoji: "👢" },
  { name: 'Surprise footbridge', color: ["yellow", "green", "blue"], emoji: "🎁" },
  { name: 'Disc bridge', color: ["yellow", "green", "blue"], emoji: "💿" },
  { name: 'Mushrooms', color: ["yellow", "green"], emoji: "🍄" },
  { name: 'Lengthwise boards', color: ["yellow", "green"], emoji: "📋" },
  { name: 'Alternated swings', color: ["yellow", "green", "blue", "red", "black"], emoji: "🔄" },
  { name: 'Dominoes', color: ["blue", "red", "black"], emoji: "🀄" },
  { name: 'Moving bridge', color: ["blue", "red", "black"], emoji: "🚠" },
  { name: 'Foot obstacle', color: ["yellow", "green"], emoji: "🚧" },
  { name: 'DNA bridge', color: ["red", "black"], emoji: "🧬" },
  { name: 'Alphabet footbridge', color: ["yellow", "green"], emoji: "🔡" },
  { name: 'Gothic footbridge', color: ["yellow", "green", "blue"], emoji: "🏰" },
  { name: 'Accordion footbridge', color: ["yellow", "green", "blue"], emoji: "🪗" },
  { name: 'Stilts', color: ["blue", "red", "black"], emoji: "🦒" },
  { name: 'Tip over trunks', color: ["yellow", "green", "blue"], emoji: "⚠️" },
  { name: 'Wazzah jump', color: ["yellow", "green", "blue", "red", "black"], emoji: "🏃" },
  { name: 'Pirogue bridge', color: ["blue", "red"], emoji: "🛶" },
  { name: 'Rolling footbridge', color: ["red", "black"], emoji: "🎡" },
  { name: 'Swingplates', color: ["yellow", "green", "blue"], emoji: "🛹" },
  { name: 'Wire-fiber horizontal ladder', color: ["yellow", "green", "blue"], emoji: "🧵" },
  { name: 'Zigzag footbridge', color: ["yellow", "green", "blue"], emoji: "⚡" },
  { name: 'Zigzag swings', color: ["yellow", "green", "blue", "red", "black"], emoji: "↔️" },
  { name: 'Balanced ropes', color: ["blue", "red", "black"], emoji: "➰" },
  { name: 'Flea’s jump', color: ["yellow", "green", "blue"], emoji: "🦗" },
  { name: 'High net', color: ["yellow", "green", "blue", "red", "black"], emoji: "🧗" },
  { name: 'Ropes with trays', color: ["red", "black"], emoji: "🥞" },
  { name: 'Hanging trunks', color: ["blue", "red", "black"], emoji: "🪝" },
  { name: 'Rope bridge', color: ["blue", "red", "black"], emoji: "🪢" },
  { name: 'In-line rope bridge', color: ["blue", "red", "black"], emoji: "➖" },
  { name: 'Zigzag rope bridge', color: ["blue", "red", "black"], emoji: "〽️" },
  { name: 'Alternated rope bridge', color: ["blue", "red", "black"], emoji: "📎" },
  { name: 'Pyramids', color: ["red", "black"], emoji: "🔺" },
  { name: 'Balanced jumps', color: ["blue", "red", "black"], emoji: "🦘" },
  { name: 'Parrot’s trunk 45DEG', color: ["red", "black"], emoji: "🦜" },
  { name: 'Simple parrot’s trunk', color: ["blue", "red", "black"], emoji: "🦜" },
  { name: 'Hanging Swings', color: ["blue", "red", "black"], emoji: "🎐" },
  { name: 'Hanging parallell stirrups', color: ["red", "black"], emoji: "👣" },
  { name: 'Hanging discs', color: ["blue", "red", "black"], emoji: "💿" },
  { name: 'Lateral trapeze', color: ["red", "black"], emoji: "🎪" },
  { name: 'Floating nets', color: ["red", "black"], emoji: "☁️" },
  { name: 'Alternated floating net', color: ["blue", "red", "black"], emoji: "☁️" },
  { name: 'Sliding net', color: ["yellow", "green", "blue", "red", "black"], emoji: "⛷️" },
  { name: 'Ambush', color: ["blue", "red", "black"], emoji: "🥷" },
  { name: 'Vertical Net', color: ["yellow", "green", "blue", "red", "black"], emoji: "🏁" },
  { name: 'Popeae beam', color: ["red", "black"], emoji: "⚓" },
  { name: 'Zig-zag trapeziums', color: ["red", "black"], emoji: "📐" },
  { name: 'Alternated trapeziums', color: ["blue", "red", "black"], emoji: "📏" },
  { name: 'Flying carpet', color: ["blue", "red"], emoji: "🧞" },
  { name: 'Tilting ropes', color: ["red", "black"], emoji: "☯️" },
  { name: 'Slalom ropes', color: ["yellow", "green", "blue", "red", "black"], emoji: "⛷️" },
  { name: 'Passage of Fisherman', color: ["blue", "red"], emoji: "🎣" },
  { name: 'Hanging Swingplates', color: ["blue", "red", "black"], emoji: "🛸" },
  { name: 'Elastic Trapeziums', color: ["red", "black"], emoji: "🤸" },
  { name: 'Tibetian bridge', color: ["yellow", "green", "blue", "red", "black"], emoji: "🏔️" },
  { name: 'Acrobat ropes', color: ["black"], emoji: "🎭" },
  { name: 'Hanging stirrups', color: ["red", "black"], emoji: "🧲" },
  { name: 'Popeye with swings', color: ["black"], emoji: "💪" },
  { name: 'Popeye', color: ["black"], emoji: "⚓" },
  { name: 'Slalom planks', color: ["yellow", "green", "blue", "red", "black"], emoji: "🛹" },
  { name: 'Climbing planks', color: ["blue", "red", "black"], emoji: "🧗" },
  { name: 'Balanced ropes (2-ends)', color: ["blue", "red", "black"], emoji: "⚖️" },
  { name: 'Horizontal climbingwall', color: ["yellow", "green"], emoji: "🧗" },
  { name: 'Arms logs', color: ["blue", "red", "black"], emoji: "🤳" },
  { name: 'Spider net', color: ["yellow", "green"], emoji: "🕷️" },
  { name: 'Wave bridge', color: ["green", "blue"], emoji: "🌊" },
  { name: 'Uneven Circles', color: ["blue", "red"], emoji: "⭕" },
  { name: 'Floating ropes', color: ["blue", "red", "black"], emoji: "🎈" },
  { name: 'Hanging Logs', color: ["blue", "red", "black"], emoji: "🎋" },
  { name: 'Jaggy Swings', color: ["black"], emoji: "🦷" },
  { name: 'Floating horizontal footbridge', color: ["yellow", "green", "blue", "red", "black"], emoji: "🚢" },
  { name: 'Floating ladder', color: ["red", "black"], emoji: "🆙" },
  { name: 'Sliding steps', color: ["yellow", "green"], emoji: "📉" },
  { name: 'Multiple sliding steps', color: ["green", "blue", "red", "black"], emoji: "📈" },
  { name: 'Skittles', color: ["yellow", "green", "blue"], emoji: "🎳" },
  { name: 'Laying trunk', color: ["yellow", "green"], emoji: "🍂" },
  { name: 'Sledge', color: ["yellow", "green", "blue"], emoji: "🛷" },
  { name: 'Cocos nut ball', color: ["yellow", "green", "blue", "red", "black"], emoji: "🥥" },
  { name: 'Surf', color: ["blue", "red", "black"], emoji: "🏄" },
  { name: 'Tightrope rope', color: ["yellow", "green", "blue", "red", "black"], emoji: "🧶" },
  { name: 'X-planks rolling', color: ["blue", "red", "black"], emoji: "✖️" },
  { name: 'Rolling parrot', color: ["green", "blue"], emoji: "🦜" },
  { name: 'Flying stirrups France', color: ["red", "black"], emoji: "🇫🇷" },
  { name: 'Rolling basket', color: ["yellow", "green", "blue"], emoji: "🧺" },
  { name: 'Rolling trapeze', color: ["green", "blue", "red"], emoji: "🤹" },
  { name: 'Flying stirrup', color: ["blue", "red", "black"], emoji: "👟" },
  { name: 'Lift', color: ["blue", "red", "black"], emoji: "🛗" },
  { name: 'Mini Tarzan', color: ["blue", "red", "black"], emoji: "🦁" },
  { name: 'Flying Trapeze', color: ["blue", "red", "black"], emoji: "🦅" },
  { name: 'Tarzan jump', color: ["red", "black"], emoji: "🌴" },
  { name: 'Unicycle', color: ["blue", "red", "black"], emoji: "🚲" },
  { name: 'Tree bike', color: ["blue", "red"], emoji: "🚵" },
  { name: 'Tightrope walk', color: ["yellow", "green", "blue", "red", "black"], emoji: "🤸" },
];
